### ISSUE TITLE
iterm import fails

### ISSUE THREAD

**Issue by IoannisTM** [sainnhe/dotfiles#6]
Hello,

I really like your theme colors
I tried to download the Gruvbox material, eveforest and sonokai,
but when I try to import them to iterm it fails with the message "The selected file could not be read or did not contain a valid color scheme."
any ideas?

Thanks

**Comment by sainnhe** [comment]
I have no idea what's going on, iterm2 color scheme files work nicely on my machine.

**Comment by IoannisTM** [comment]
Oh my god I am so stupid. SO stupid
please close this, or even better delete it from the face of this earth. I was accidentaly copying the html code of the webpage for some reason instead of the config file for the profile, don't ask me why and how, we said I am stupid !!

Thanks for replying though!! love your themes.
