### ISSUE TITLE
Alacritty configuration

### ISSUE THREAD

**Issue by H4ppy-04** [sainnhe/dotfiles#8]
Hey @sainnhe,

Firstly, I love your configuration, It's one of the best ones I've seen. I think [r/unixporn](https://reddit.com/r/unixporn/) would love it! :trophy: 

I would greatly appreciate your Alacritty configuration, if your comfortable publishing it?

Cheers,
Josh.

**Comment by sainnhe** [comment]
Thanks for your appreciation :)

I don't use alacritty honestly, I use iterm2 on macOS and use kitty on Linux, but I've posted some github gist for some alacritty color schemes.
